### ISSUE TITLE
Testing `src`

### ISSUE THREAD

**Issue by brettz9** [ayZagen/vue3-rollup-test#3]
Hi,

I'm looking for a way to easily check whether `src` actually works. Is there a way to get it working without all the webpack config?

When I tried a global install of `@vue/cli` and then running `vue serve src/Test.vue` (which is supposed to be an easy, though non-production-ready method of testing apps), I get this error:

> This dependency was not found:
>
> * vue in ./src/Test.vue

...despite the fact that I have run a local `npm install` and `vue` is in dependencies.

~If this route won't work, maybe some minimal Webpack could be added?~

I see one can just run in the browser, so may file a PR to that effect.

**Comment by ayZagen** [comment]
For vue/cli you need to use  [vue-cli-plugin-vue-next](https://github.com/vuejs/vue-cli-plugin-vue-next) which doesn't support typescript yet. Let me add rollup-plugin-serve

**Comment by ayZagen** [comment]
Done with https://github.com/ayZagen/vue3-rollup-test/commit/d2dbfd05126666a4de2fbd321a69b1698c87b2e7

**Comment by brettz9** [comment]
Good to know, thanks! And hadn't known about `rollup-plugin-serve`, seems a good solution...

FWIW, I found a regular browser HTML envrionment as another helpful, no-config prototyping option: https://github.com/pathscale/vue3-ui/tree/master/example

**Comment by brettz9** [comment]
Btw, FWIW, I tried with a local install of `vue-cli-plugin-vue-next` and get the same error (with `vue serve <myComponentPath>`) about the `vue` dependency not being found (despite it being in `package.json` and being the vue-next (3.0 beta) version). I guess maybe the CLI plugin may still have some problems.
